wipe     = true # 先删除之前自动生成的文件再重新生成
no-tests = true # 不生成测试代码
add-global-variants = true # 生成使用全局数据源的方法，也就是带 G 后缀的方法
add-panic-variants = true # 生成使用当 error 不为 nil 时 panic 的方法，也就是带 P 后缀的方法
no-context = true # 不需要上下文参数
no-hooks = true
[mysql]
dbname = "go_test"
host = "localhost"
port = 3306
user = "root"
pass = "123456"
charset = "utf8mb4"
sslmode = "skip-verify" # 禁用 SSL/TLS 验证
#whitelist = ["elecard_coupon_job_history"]
whitelist = ["table_test"]
#schema = "elecard_work_order"
#exclude_tables = ["table1", "table2"]
