// Package model Code generated by sql2struct. https://github.com/starfishs/sql2struct
package model

import "time"

type ToDo struct {
	ID        int64     `gorm:"column:id" json:"id"`
	Label     string    `gorm:"column:label" json:"label"`
	Value     string    `gorm:"column:value" json:"value"`
	Disable   uint8     `gorm:"column:disable" json:"disable"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName the name of table in database
func (t *ToDo) TableName() string {
	return "to_do"
}
