// Package model Code generated by sql2struct. https://github.com/starfishs/sql2struct
package model

import "time"

type Users struct {
	ID        int64     `gorm:"column:id" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`         // 用户名称
	Mobile    string    `gorm:"column:mobile" json:"mobile"`     // 用户手机号
	Password  string    `gorm:"column:password" json:"password"` // 用户密码
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt time.Time `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName the name of table in database
func (t *Users) TableName() string {
	return "users"
}
